[tool.poetry]
name = "cryptobot-python"
version = "0.1.4"
description = "Non official, but friendly CryptoBot library for the Python language"
authors = ["Reinier Hernández <sasuke.reinier@gmail.com>"]
license = "MIT"
readme = "README.rst"
packages = [
    { include = "cryptobot" }
]

[tool.poetry.dependencies]
python = "^3.9"
pip = "24.0"
bump2version = ">=1.0.1,<1.1.0"
wheel = ">=0.38.4,<0.44.0"
watchdog = ">=2.2.1,<4.1.0"
tox = ">=4.4.8,<4.5.0"
sphinx = ">=6.1.3,<6.2.0"
twine = ">=4.0.2,<5.1.0"
httpx = ">=0.23.3,<0.24.0"
python-dotenv = ">=0.21.0,<1.1.0"
uvicorn = "0.27.1"
colorama = "0.4.6"
fastapi = "0.110.0"

[tool.poetry.group.dev.dependencies]
flake8 = ">=6.0.0,<7.1.0"
coverage = ">=7.2.2,<7.5.0"
pytest = ">=7.2.0,<8.2.0"
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
